language: php
os:
- linux
dist:
- trusty
php:
- '7.0'
- '7.1'
before_script:
- composer install
script:
- phpunit
deploy:
  provider: codedeploy
  access_key_id: AKIAIUZ673MBE2OIDZPQ
  secret_access_key:
    secure: "L8vQ5WRcPAR3XYW5qXjUvlNyAmpQ+baUsq/YLl1NLrVqxqRTnn0ieNuPLKtIvcKMqUacHSCOYXmL9l+SGv23ND0/pNoKEyhRBsk9xQ5qm3KUEXjYmupjO876KSAWPU9IanNbjpKcN28d7Wbp+bfkhUhkEsvADKyTNXjenmrvik+xFrmcgm8SwFiriD2ou59w5f5mo5pVcI0qJpAIY8AYWlXGy6WnGLRktldZ4kPzrNP39ioYXuBmmQ6T9HTjfFtdml3lx5fhxexoL993VxkkPxST7Yy0NhfE8geNIaPOmuxXdzrp+qR/0moCiC5Y54ZB5zzJDcj9ZobYbb6xtbPmIuFWOmTLyiNFgNpY1bqBJVx2Jhw/09cRdY9tNnWpXyeSA/NE05r51LHW4p92lLTWke8Ush4CQ3m9NA88Gtb1aFTD2EmBRteYGwGA03QZ6YxDi7b0BFWynINqihhUHXlmG989VFX26FhZcRZVaMY+PYzf7yJO3vtpp15Yt7p8uT/rYJH5Lp+nacBwg6vCwLzNmAN24HWx3P83etPFhMEB2pjFmvEm6vgk0xSoh7rTOwtr33xO8fehC90WC1NECEOL3O/AIVnvN5QKG6FQ658cyYjoXPqvTmpgcsytavrmZU31ddQLdHsWwfnkftDOwbrQm240JY8JOVl8aw43+tLL47Y="
  bucket: "codedeploy-web-test"
  key: latest/MyApp.zip
  application: web-test
  deployment_group: master
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: PiknaWB9oNXHHE8QcxLp7yBUKQbvKotggzLz3Bgsf9spqU6bZ+axC3K+8KK6hRswxGdBoX1249YvP8xbyDm09T1ODZbiOnRaqEQ2RIZYNvD/LPpu5jX3k9M0X/7tMGg0cctXJx8XbzKhs2y78+uGWfXqvnw4C/DyDXT6CxadP7DVB0MTaPVA4vNISDQpLmZ85K3pGr2W+tHTrFxFLVwohCqUzRBI9PVkvrRHTeun168BmwoFMxNprEuj1K0La47ajIE1Tdb45hUUjq6uOFaYnZdVFSUH+1CxRITFKe9DQ8aOpbs47Je6pbq8REsx5F4SuwrXWAmWhYykvNvQngSymOiVFLrPx53Ge925oJwKVPkfWHilhS/sV5wYVitBSuLokETwcWodxQ5TXX48Kh8a7auU8rubyBO6TWA++t11a7CgT4xQaYCRI5XyDUp2DnJvQc08EmLdS/dh5MKtMp4eF4voyMQatUA1vVFjz11hzQ9cDxrctBrxlbZo99HAOx+XmOmdZknZkX/K241750co5ZVZbR+LeRLBGHOJO9rHJfeWzdVRNEDuNH9/xgtL3RXUseL29anAh6WCEbbYaiCxzNgpBE0QQK5fkunA9UESGGY5Aeoq8C6kOCjgrXaNQXBwGr77F5ZRmHQo5fS3/F5zmP6izoT1mSYNJtmVNeQSO9s=
